wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1631545147
    t:
      1:
      - 1
      - 3
      4: 3.9.6
      5: 0.12.1
      8:
      - 3
      - 5
